### ISSUE TITLE
Will slides be updated to version used in Node Interactive 2016?

### ISSUE THREAD

**Issue by knksmith57** [joyeecheung/v8-gc-talk#1]
Hi Joyee!

First off, thank you _so_ much for these excellent slides. This is the most comprehensive resource I've been able to find on GC in V8.

I attended your talk, [Are Your V8 Garbage Collection Logs Speaking To You?](http://sched.co/8V05), today at Node Interactive 2016. The slides presented there seem a little more detailed than the ones [posted here](https://github.com/joyeecheung/v8-gc-talk/blob/master/Are%20Your%20V8%20GC%20Logs%20Speaking%20to%20You.pdf). Will you be posting those here?

**Comment by joyeecheung** [comment]
Hi, I uploaded the slides for Node Interactive to another repo: https://github.com/joyeecheung/talks/blob/master/node_interactive_2016/are_your_v8_garbage_collection_logs_speaking_to_you_updated.pdf  

FYI the slides and code in this repo have some data not available from the community version of Node.js(they are from alinode, our internal version of node). The slides for Node Interactive don't.

BTW I am translating a few blog posts I've written into English as part of the documentation for https://github.com/aliyun-node/v8-gc-log-parser (the posts in Chinese are http://alinode.aliyun.com/blog/37 and http://alinode.aliyun.com/blog/38). Those go into more details than my talk at Node Interactive.

**Comment by knksmith57** [comment]
Thank you very much! Looking forward to the translated blog posts and more talks and references from you and alibaba in the future!
